### ISSUE TITLE
cant use

### ISSUE THREAD

**Issue by Tira-tw** [RosneBurgerworks/lmaobox-navbot#1]
[Warning] C:\Users\user\AppData\Local//LNXlib.lua:163: Command 'pf' already exists and will be overwritten!
[Warning] C:\Users\user\AppData\Local//LNXlib.lua:163: Command 'pf_auto' already exists and will be overwritten!
C:\Users\user\AppData\Local\Lmaobot.lua:473: Failed to read nav file:

**Comment by Tira-tw** [comment]
> put map nav in tf/maps folder

[Navigation.lua](https://github.com/RosneBurgerworks/lmaobox-navbot/blob/main/Lmaobot/Navigation.lua)this?

**Comment by Tira-tw** [comment]
> > > put map nav in tf/maps folder
> > 
> > 
> > [Navigation.lua](https://github.com/RosneBurgerworks/lmaobox-navbot/blob/main/Lmaobot/Navigation.lua)this?
> 
> this https://github.com/RosneBurgerworks/rosnebot-database/tree/master/nav%20meshes
> 
> copy it into this dir (there is alot os .bsp file) ![image](https://private-user-images.githubusercontent.com/54238880/299712965-aad69c9b-d5d7-471a-a4fc-d74f73823e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYxOTgsIm5iZiI6MTcwNjE5NTg5OCwicGF0aCI6Ii81NDIzODg4MC8yOTk3MTI5NjUtYWFkNjljOWItZDVkNy00NzFhLWE0ZmMtZDc0ZjczODIzZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmY2E1YWYwMmE1MzQ4OTk4OWFhYmJkYjE4MzM0ZGJkN2I2NjI5YzAyOWVjOTZhZGQxMmFlNjU4MDQxNzA5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpoWTcSbsb-ESqNEVdoP58P-uJoVy2qgxVxboOFN2CM)

is all?

**Comment by Tira-tw** [comment]
![image](https://github.com/RosneBurgerworks/lmaobox-navbot/assets/64715639/7b5ae997-148f-4cd1-8bef-107398fc9be3)

**Comment by Tira-tw** [comment]
> > > > > put map nav in tf/maps folder
> > > > 
> > > > 
> > > > [Navigation.lua](https://github.com/RosneBurgerworks/lmaobox-navbot/blob/main/Lmaobot/Navigation.lua)this?
> > > 
> > > 
> > > this https://github.com/RosneBurgerworks/rosnebot-database/tree/master/nav%20meshes
> > > copy it into this dir (there is alot os .bsp file) ![image](https://private-user-images.githubusercontent.com/54238880/299712965-aad69c9b-d5d7-471a-a4fc-d74f73823e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTYxOTgsIm5iZiI6MTcwNjE5NTg5OCwicGF0aCI6Ii81NDIzODg4MC8yOTk3MTI5NjUtYWFkNjljOWItZDVkNy00NzFhLWE0ZmMtZDc0ZjczODIzZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1MTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmY2E1YWYwMmE1MzQ4OTk4OWFhYmJkYjE4MzM0ZGJkN2I2NjI5YzAyOWVjOTZhZGQxMmFlNjU4MDQxNzA5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CpoWTcSbsb-ESqNEVdoP58P-uJoVy2qgxVxboOFN2CM)
> > 
> > 
> > is all?
> 
> yea but rosne lua is still shit

![image](https://github.com/RosneBurgerworks/lmaobox-navbot/assets/64715639/fe5d84d5-ab0a-42c8-af75-1ac11b3b5039)

**Comment by Tira-tw** [comment]
> wait @rosne-gamingyt for fix

so now cant use?

**Comment by rosne-gamingyt** [comment]
You can only be on payload or CTF so far @Tira-tw

**Comment by rosne-gamingyt** [comment]
And must have nav meshes

**Comment by Tira-tw** [comment]
> And must have nav meshes

have video?

**Comment by rosne-gamingyt** [comment]
I have added it to readme, also use the new version of the lua.

**Comment by Tira-tw** [comment]
> I have added it to readme, also use the new version of the lua.

can use! but @@
![image](https://github.com/RosneBurgerworks/lmaobox-navbot/assets/64715639/a2be8615-d647-493e-8235-0f5cc51b3ebe)

**Comment by rosne-gamingyt** [comment]
> > I have added it to readme, also use the new version of the lua.
> 
> can use! but @@ ![image](https://private-user-images.githubusercontent.com/64715639/300149959-a2be8615-d647-493e-8235-0f5cc51b3ebe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMzU0MDgsIm5iZiI6MTcwNjMzNTEwOCwicGF0aCI6Ii82NDcxNTYzOS8zMDAxNDk5NTktYTJiZTg2MTUtZDY0Ny00OTNlLTgyMzUtMGY1Y2M1MWIzZWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDA1NTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2Mzk0YjdkNjAzZTEzYTFjZWQwYzc1ZTNlMTZkN2IwNDIxMGUyYmFjOTYwNDUwNGEwNjE0ZGIxNjBmMmVjYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WaDt6RIZlB9Et-CgOPaBIj2ix0Dq4lfREMOglGLZxmc)

thats just mem leak being shit, fix coming soon for that
