### ISSUE TITLE
lua not woriking 

### ISSUE THREAD

**Issue by Hundaimy** [RosneBurgerworks/lmaobox-navbot#15]
Hello. I have a problem with your Lua, I can't run it properly. Every time I run it I get an error in the console:

-[Warn  22:44:08] Lmaobot: Could not find a start node near the player's position.

the bot just doesn't work, it just spams my console with this error. Most likely I'm just stupid please explain how to fix this. I did everything according to the instructions and there is also a lnxLib library. 
Thanks!

**Comment by SaltEatersAnonymous** [comment]
What LMAOBox build are you using? (stable, beta)

**Comment by Hundaimy** [comment]
the problem has already been solved, I just transferred all the navigation meshes created by MakeNavs.bat to the folder with the game maps. The instructions don't say anything about this, I think it will need to be supplemented.
If you're interested, I use the standard version of the loader. Thanks
