### ISSUE TITLE
Memory going haywire.

### ISSUE THREAD

**Issue by AssociatedWithN** [RosneBurgerworks/lmaobox-navbot#19]
I touch men

**Comment by EdwardTeachTF** [comment]
Huh

**Comment by EdwardTeachTF** [comment]
How to edit <@707645826683633746> @booze.

**Comment by EdwardTeachTF** [comment]
I am talking about this:
<@&1139673826674880563>![image-79.png](https://github.com/RosneBurgerworks/lmaobox-navbot/assets/157900452/8bc9d2f0-5abb-4039-b7e3-fb7903f4bb91)

**Comment by rosne-gamingyt** [comment]
this has been fixed
